[ffmpeg-encoder-plugin-resolve]
src.github = "EdvinNilsson/ffmpeg_encoder_plugin"
src.prefix = "v"
fetch.url = "https://github.com/EdvinNilsson/ffmpeg_encoder_plugin/releases/download/v$ver/ffmpeg_encoder_plugin.dvcp.bundle.zip"

[archi]
src.github = "archimatetool/archi.io"
fetch.url = "https://github.com/archimatetool/archi.io/releases/download/$ver/Archi-Linux64-$ver.tgz"

[reverser_ai]
src.git = "https://github.com/mrphrazer/reverser_ai.git"
fetch.github = "mrphrazer/reverser_ai"

[ida-chat-plugin]
src.git = "https://github.com/HexRaysSA/ida-chat-plugin.git"
fetch.github = "HexRaysSA/ida-chat-plugin"

[sstv]
src.git = "https://github.com/colaclanth/sstv.git"
fetch.github = "colaclanth/sstv"

[volatility-toolkit]
src.github = "gl0bal01/volatility-toolkit"
fetch.github = "gl0bal01/volatility-toolkit"

[registry-spy]
src.github = "andyjsmith/Registry-Spy"
fetch.github = "andyjsmith/Registry-Spy"

[evolve]
src.github = "JamesHabben/evolve"
fetch.github = "JamesHabben/evolve"

[dnspy]
src.github = "dnSpyEx/dnSpy"
fetch.url = "https://github.com/dnSpyEx/dnSpy/releases/download/v$ver/dnSpy-netframework.zip"
src.github_use_latest_release = true
src.prefix = "v"

[stremio-enhanced]
src.github = "REVENGE977/stremio-enhanced"
fetch.url = "https://github.com/REVENGE977/stremio-enhanced/releases/download/v$ver/Stremio.Enhanced-$ver.AppImage"
src.github_use_latest_release = true
src.prefix = "v"

[ctfd-parser]
src.github = "p0dalirius/ctfd-parser"
fetch.github = "p0dalirius/ctfd-parser"

[libesedb]
src.git = "https://github.com/libyal/libesedb.git"
fetch.git = "https://github.com/libyal/libesedb.git"

[libfsntfs]
src.git = "https://github.com/libyal/libfsntfs.git"
fetch.git = "https://github.com/libyal/libfsntfs.git"

[sidr]
src.github = "strozfriedberg/sidr"
fetch.github = "strozfriedberg/sidr"

[ese-database-view]
src.webpage = "https://www.nirsoft.net/utils/ese_database_view.html"
src.regex = "Version ([0-9.]+)"
fetch.url = "https://www.nirsoft.net/utils/esedatabaseview.zip"

[trakt-scrobbler]
src.github = "iamkroot/trakt-scrobbler"
fetch.github = "iamkroot/trakt-scrobbler"

[apk-mitm]
src.github = "niklashigi/apk-mitm"
fetch.github = "niklashigi/apk-mitm"


[rem]
src.github = "liriliri/rem"
src.prefix = "v"
fetch.url = "https://github.com/liriliri/rem/releases/download/v$ver/REM-$ver-linux-x86_64.AppImage"

[scrollmpris]
src.git = "https://github.com/BEST8OY/ScrollMPRIS.git"
fetch.github = "BEST8OY/ScrollMPRIS"

[monkeylauncher]
src.github = "SaruM4N3/MonkeyLauncher"
fetch.github = "SaruM4N3/MonkeyLauncher"

[linoffice]
src.github = "eylenburg/linoffice"
fetch.github = "eylenburg/linoffice"

[nordvpn]
src.webpage = "https://repo.nordvpn.com/deb/nordvpn/debian/dists/stable/main/binary-amd64/Packages"
src.regex = "Package: nordvpn\nVersion: ([0-9.]+)"
fetch.url = "https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/n/nordvpn/nordvpn_$ver_amd64.deb"

[harbor]
src.github = "harborstremio-linux/harbor-linux-builds"
src.github_use_latest_release = true
src.prefix = "v"
fetch.url = "https://github.com/harborstremio-linux/harbor-linux-builds/releases/download/v$ver/Harbor_$ver_amd64.deb"

[jackify]
src.github = "Omni-guides/Jackify"
src.prefix = "v"
fetch.url = "https://github.com/Omni-guides/Jackify/releases/download/v$ver/Jackify.AppImage"

[steamidra]
src.github = "Midrags/SFF"
fetch.github = "Midrags/SFF"

[analyzeMFT]
src.github = "rowingdude/analyzeMFT"
fetch.github = "rowingdude/analyzeMFT"

[nuvio]
src.github = "blarns/NuvioForLinux"
src.prefix = "v"
fetch.url = "https://github.com/blarns/NuvioForLinux/releases/download/v$ver/Nuvio-$ver-x86_64.AppImage"

[onlinefix-linux]
src.github = "ZzEdovec/onlinefix-linux"
src.prefix = "v"
fetch.url = "https://github.com/ZzEdovec/onlinefix-linux/releases/download/v$ver/OFMELauncher.jar"

[hayabusa]
src.github = "Yamato-Security/hayabusa"
fetch.url = "https://github.com/Yamato-Security/hayabusa/releases/download/v$ver/hayabusa-$ver-lin-x64-gnu.zip"
src.prefix = "v"

[ctfbridge]
src.git = "https://github.com/bjornmorten/ctfbridge.git"
fetch.git = "https://github.com/bjornmorten/ctfbridge.git"

[ctf-dl]
src.git = "https://github.com/bjornmorten/ctf-dl.git"
fetch.git = "https://github.com/bjornmorten/ctf-dl.git"

[vorion]
src.git = "https://github.com/Zexolver/Vorion.git"
fetch.git = "https://github.com/Zexolver/Vorion.git"

[vol-rs]
src.github = "daffainfo/vol-rs"
fetch.github = "daffainfo/vol-rs"
