# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  analyzeMFT = {
    pname = "analyzeMFT";
    version = "v3.1.1.0";
    src = fetchFromGitHub {
      owner = "rowingdude";
      repo = "analyzeMFT";
      rev = "v3.1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-piCH88uQaRt3U1g+hfkBL1wVrN5C9v1sXVaAV6YQioo=";
    };
  };
  angr-management = {
    pname = "angr-management";
    version = "v9.3.3";
    src = fetchurl {
      url = "https://github.com/angr/angr-management/releases/download/v9.3.3/angr-management-v9.3.3-x86_64.AppImage";
      sha256 = "sha256-831I6hqwMMQqvil8savtRJrgzVv3oKXlfHur1jzMAs8=";
    };
  };
  angr-management-src = {
    pname = "angr-management-src";
    version = "v9.3.3";
    src = fetchFromGitHub {
      owner = "angr";
      repo = "angr-management";
      rev = "v9.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-k9N+Ok6me7gNHZ+kICnvwG366E/+v2lAGmHkUo38h5o=";
    };
  };
  apk-mitm = {
    pname = "apk-mitm";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "niklashigi";
      repo = "apk-mitm";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-wcLShZ7O20i0hzz957dNmfjvxCn5lmWObTdTRF7p+I8=";
    };
  };
  autodesk-fusion = {
    pname = "autodesk-fusion";
    version = "53b02038548f01a6e0a1fa2def0a9b545f1561c1";
    src = fetchgit {
      url = "https://codeberg.org/cryinkfly/Autodesk-Fusion-360-on-Linux.git";
      rev = "53b02038548f01a6e0a1fa2def0a9b545f1561c1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-k3ECZzYHV5gJq4qDR9YcYMoUGK4YW94iVGp62K5KbSM=";
    };
    date = "2026-06-20";
  };
  ctf-dl = {
    pname = "ctf-dl";
    version = "db23c9dfe19429f3dfd75cf788cd54a8185f82e9";
    src = fetchgit {
      url = "https://github.com/bjornmorten/ctf-dl.git";
      rev = "db23c9dfe19429f3dfd75cf788cd54a8185f82e9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0n6CQAkpQLFJZsM767TxPcLIzzIfFyIMsf40pW5gNzc=";
    };
    date = "2025-10-12";
  };
  ctfbridge = {
    pname = "ctfbridge";
    version = "11f126d621e05dfe1e0b5b9cc5bd4c2f94220029";
    src = fetchgit {
      url = "https://github.com/bjornmorten/ctfbridge.git";
      rev = "11f126d621e05dfe1e0b5b9cc5bd4c2f94220029";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-gNuIVrRVn0zrTkoZnDNEjUY9QissWbGgkbNaLOBfd+8=";
    };
    date = "2026-03-06";
  };
  ctfd-parser = {
    pname = "ctfd-parser";
    version = "1.1";
    src = fetchFromGitHub {
      owner = "p0dalirius";
      repo = "ctfd-parser";
      rev = "1.1";
      fetchSubmodules = false;
      sha256 = "sha256-2Rbe97xz48r22X61jjnwFPBiN0dIeUKd4zcSJxBrSd0=";
    };
  };
  dnspy = {
    pname = "dnspy";
    version = "6.6.0";
    src = fetchurl {
      url = "https://github.com/dnSpyEx/dnSpy/releases/download/v6.6.0/dnSpy-netframework.zip";
      sha256 = "sha256-Lq239JMa0YgtEEd89XGF0ojKzG46v5lY565zwKDzHdE=";
    };
  };
  ese-database-view = {
    pname = "ese-database-view";
    version = "1.79";
    src = fetchurl {
      url = "https://www.nirsoft.net/utils/esedatabaseview.zip";
      sha256 = "sha256-tjbPXj7aom6tJE9YxK43LJoopQXRego6btTc5BusOr8=";
    };
  };
  evolve = {
    pname = "evolve";
    version = "v1.6";
    src = fetchFromGitHub {
      owner = "JamesHabben";
      repo = "evolve";
      rev = "v1.6";
      fetchSubmodules = false;
      sha256 = "sha256-IRO2pqRK3pMqv49T4U/aAccilIA9pdVURFTlSeXy5D4=";
    };
  };
  ffmpeg-encoder-plugin-resolve = {
    pname = "ffmpeg-encoder-plugin-resolve";
    version = "1.4.0";
    src = fetchurl {
      url = "https://github.com/EdvinNilsson/ffmpeg_encoder_plugin/releases/download/v1.4.0/ffmpeg_encoder_plugin.dvcp.bundle.zip";
      sha256 = "sha256-0Qzsd3h/JtjX8WzkFUBdFIxg/HUKFvP1p8K0b0Ai8UY=";
    };
  };
  harbor = {
    pname = "harbor";
    version = "0.9.21";
    src = fetchurl {
      url = "https://github.com/harborstremio-linux/harbor-linux-builds/releases/download/v0.9.21/Harbor_0.9.21_amd64.deb";
      sha256 = "sha256-j3TuBP4WDQj64k47LPRAiErchiQ4kKiuZ4cSMmKYkT0=";
    };
  };
  hayabusa = {
    pname = "hayabusa";
    version = "4.0.0";
    src = fetchurl {
      url = "https://github.com/Yamato-Security/hayabusa/releases/download/v4.0.0/hayabusa-4.0.0-lin-x64-gnu.zip";
      sha256 = "sha256-ETfifHleg/iDfJYvITbPFjSmemVde6jvqLLTijO6CbQ=";
    };
  };
  ida-chat-plugin = {
    pname = "ida-chat-plugin";
    version = "883f9b3550725d81eed80c25dd28c75b320f22c7";
    src = fetchFromGitHub {
      owner = "HexRaysSA";
      repo = "ida-chat-plugin";
      rev = "883f9b3550725d81eed80c25dd28c75b320f22c7";
      fetchSubmodules = false;
      sha256 = "sha256-ueGelV0KZhE4k7O5VsBTSfZgWz/gm9Lr3CdIYl99Yd8=";
    };
    date = "2026-04-20";
  };
  ist-fenix-auto-enroller = {
    pname = "ist-fenix-auto-enroller";
    version = "v0.2.1";
    src = fetchFromGitHub {
      owner = "ang3lo-azevedo";
      repo = "ist-fenix-auto-enroller";
      rev = "v0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-uDsV1B3mp9MLezWf9GNoJRXT9vlo1AfCDZzyOi+jG7E=";
    };
  };
  jackify = {
    pname = "jackify";
    version = "0.8.0";
    src = fetchurl {
      url = "https://github.com/Omni-guides/Jackify/releases/download/v0.8.0/Jackify.AppImage";
      sha256 = "sha256-NZWeoijFAl4xVoF7Gl7TRx3DTxcb6fTk4KFjFdRCt5o=";
    };
  };
  libesedb = {
    pname = "libesedb";
    version = "cf49b6d420d4a44dcd6355bc0d6b36f9f580f350";
    src = fetchgit {
      url = "https://github.com/libyal/libesedb.git";
      rev = "cf49b6d420d4a44dcd6355bc0d6b36f9f580f350";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TTDVXT+c/l1CU2UWWppA/OPu8YxP4AgqItCW0/FtFPU=";
    };
    date = "2026-07-04";
  };
  libfsntfs = {
    pname = "libfsntfs";
    version = "0d2d9d7282e4910eba6b9ff4933fe421a3f39c9a";
    src = fetchgit {
      url = "https://github.com/libyal/libfsntfs.git";
      rev = "0d2d9d7282e4910eba6b9ff4933fe421a3f39c9a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9MvoDgwP/9iVSZvo1ik2eYLoWOMYKoGWrvKEesvFbDQ=";
    };
    date = "2026-08-27";
  };
  linoffice = {
    pname = "linoffice";
    version = "v2.2.10";
    src = fetchFromGitHub {
      owner = "eylenburg";
      repo = "linoffice";
      rev = "v2.2.10";
      fetchSubmodules = false;
      sha256 = "sha256-kLZEUZDz4rvUmVqvKVdMpAAmNdja56i81GaQ9jT+BLU=";
    };
  };
  monkeylauncher = {
    pname = "monkeylauncher";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "SaruM4N3";
      repo = "MonkeyLauncher";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-j+ZRvreZRFJKy6cQCpmGQjOSJfSoeuaWxFRE9fOjgx0=";
    };
  };
  nordvpn = {
    pname = "nordvpn";
    version = "5.3.0";
    src = fetchurl {
      url = "https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/n/nordvpn/nordvpn_5.3.0_amd64.deb";
      sha256 = "sha256-NM3qcqdclwDChblQ7S7Jasru1NYHATo6vRg2ZzH4wzQ=";
    };
  };
  nuvio = {
    pname = "nuvio";
    version = "0.3.8";
    src = fetchurl {
      url = "https://github.com/blarns/NuvioForLinux/releases/download/v0.3.8/Nuvio-0.3.8-x86_64.AppImage";
      sha256 = "sha256-oGpNnc6x1CS6fiXdW9ybQ0cC8sAPAFHzeYtHr1DLINY=";
    };
  };
  onlinefix-linux = {
    pname = "onlinefix-linux";
    version = "2.7.1";
    src = fetchurl {
      url = "https://github.com/ZzEdovec/onlinefix-linux/releases/download/v2.7.1/OFMELauncher.jar";
      sha256 = "sha256-nK5PLMBmaewaFHcQLR0lrPlvg5PJwdYcNyhCTS7cpdE=";
    };
  };
  registry-spy = {
    pname = "registry-spy";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "andyjsmith";
      repo = "Registry-Spy";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-5D6uDjcCFGtkAyMp0S3blwc5vMP39dyKWTM+nocSIm0=";
    };
  };
  rem = {
    pname = "rem";
    version = "1.4.0";
    src = fetchurl {
      url = "https://github.com/liriliri/rem/releases/download/v1.4.0/REM-1.4.0-linux-x86_64.AppImage";
      sha256 = "sha256-rL6ebeURL3dcts53xIq5olHHnEQoK9rzIPdfXbu3H/c=";
    };
  };
  reverser_ai = {
    pname = "reverser_ai";
    version = "1d572da70479ea822875b9350135d7e3402f5557";
    src = fetchFromGitHub {
      owner = "mrphrazer";
      repo = "reverser_ai";
      rev = "1d572da70479ea822875b9350135d7e3402f5557";
      fetchSubmodules = false;
      sha256 = "sha256-07bh4ofudKLKYGgHySSK4mpDstuyybKFktIfp0s8V8g=";
    };
    date = "2026-05-20";
  };
  scrollmpris = {
    pname = "scrollmpris";
    version = "d2837a9d5c6b219b60d949fca89f4aab0446bb8a";
    src = fetchFromGitHub {
      owner = "BEST8OY";
      repo = "ScrollMPRIS";
      rev = "d2837a9d5c6b219b60d949fca89f4aab0446bb8a";
      fetchSubmodules = false;
      sha256 = "sha256-mqgw4kmDqIq+gr9V8Xk4ew9dl1dzPIbrVOCUFzWcCG8=";
    };
    date = "2026-08-30";
  };
  sidr = {
    pname = "sidr";
    version = "v0.9.2";
    src = fetchFromGitHub {
      owner = "strozfriedberg";
      repo = "sidr";
      rev = "v0.9.2";
      fetchSubmodules = false;
      sha256 = "sha256-l6J+JJaFkFTDroMz6Ldnmq40OQGmEtL6l3ZFG6yk1GQ=";
    };
  };
  sstv = {
    pname = "sstv";
    version = "3e556eee8ad4c4425799cb652bac26ee58f8e113";
    src = fetchFromGitHub {
      owner = "colaclanth";
      repo = "sstv";
      rev = "3e556eee8ad4c4425799cb652bac26ee58f8e113";
      fetchSubmodules = false;
      sha256 = "sha256-s+G3MUVxEL/CwLaLk2nFcTFfRqq4Hrbj6qa/GhhzFMc=";
    };
    date = "2019-11-04";
  };
  steamidra = {
    pname = "steamidra";
    version = "v6.6.6";
    src = fetchFromGitHub {
      owner = "Midrags";
      repo = "SFF";
      rev = "v6.6.6";
      fetchSubmodules = false;
      sha256 = "sha256-75pGSL2qBJ0BsK6FLFyLk13I5nqvTgniaR6BgbYeK2o=";
    };
  };
  stremio-enhanced = {
    pname = "stremio-enhanced";
    version = "1.2.0";
    src = fetchurl {
      url = "https://github.com/REVENGE977/stremio-enhanced/releases/download/v1.2.0/Stremio.Enhanced-1.2.0.AppImage";
      sha256 = "sha256-a+knxg/rd5Ied4RVK8Gg7xeFElovJab0gqxpjs11fAU=";
    };
  };
  trakt-scrobbler = {
    pname = "trakt-scrobbler";
    version = "v1.9.0b1";
    src = fetchFromGitHub {
      owner = "iamkroot";
      repo = "trakt-scrobbler";
      rev = "v1.9.0b1";
      fetchSubmodules = false;
      sha256 = "sha256-ylgCDWmcZzz6mMBpEAj16jK1loTxQJmk9G/3Hnp9WuI=";
    };
  };
  vol-rs = {
    pname = "vol-rs";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "daffainfo";
      repo = "vol-rs";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-dbvt3vVnW9enfttNEj81C35Vbg1vj2MzFsC7GAWwxbE=";
    };
  };
  volatility-toolkit = {
    pname = "volatility-toolkit";
    version = "v2.1.1";
    src = fetchFromGitHub {
      owner = "gl0bal01";
      repo = "volatility-toolkit";
      rev = "v2.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-2HdfpF1DCn95HsArcvAeuWh5FNwjj9LxwJ/nlosHBmk=";
    };
  };
  vorion = {
    pname = "vorion";
    version = "13bf254a806f9e062e5a09e00181917288bdf7b3";
    src = fetchgit {
      url = "https://github.com/Zexolver/Vorion.git";
      rev = "13bf254a806f9e062e5a09e00181917288bdf7b3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TgU+qnbajJKZaVN27RXRxyqnEox4rpXcEmkldzr/ecg=";
    };
    date = "2025-06-15";
  };
}
