{
  pkgs,
  callPackage,
  ...
}: let
  sources = callPackage ../_sources/generated.nix {};
  inherit (pkgs) lib stdenv autoPatchelfHook makeWrapper jdk libsecret glib webkitgtk_4_1 wrapGAppsHook3 copyDesktopItems makeDesktopItem _7zz;
in
  stdenv.mkDerivation rec {
    pname = "Archi";
    version = sources.archi.version;
    src = sources.archi.src;

    buildInputs = [libsecret];

    nativeBuildInputs =
      [
        makeWrapper
        wrapGAppsHook3
        pkgs.adwaita-icon-theme
        pkgs.hicolor-icon-theme
      ]
      ++ lib.optionals stdenv.hostPlatform.isDarwin [_7zz]
      ++ lib.optionals stdenv.hostPlatform.isLinux [
        autoPatchelfHook
        copyDesktopItems
      ];

    sourceRoot =
      if stdenv.hostPlatform.isDarwin
      then "."
      else null;

    installPhase =
      if stdenv.hostPlatform.system == "x86_64-linux"
      then ''
        runHook preInstall

        mkdir -p $out/bin $out/libexec
        for f in configuration features p2 plugins Archi.ini; do
          cp -r $f $out/libexec
        done

        install -D -m755 Archi $out/libexec/Archi

        # We wrap Archi with theme environment variables
        makeWrapper $out/libexec/Archi $out/bin/Archi \
          --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [glib webkitgtk_4_1]} \
          --set WEBKIT_DISABLE_DMABUF_RENDERER 1 \
          --set GTK_THEME adwaita \
          --set XDG_CURRENT_DESKTOP GNOME \
          --prefix PATH : ${jdk}/bin \
          --prefix XDG_DATA_DIRS : "${pkgs.adwaita-icon-theme}/share:${pkgs.hicolor-icon-theme}/share"

        install -Dm444 icon.xpm $out/share/icons/hicolor/256x256/apps/archi.xpm

        runHook postInstall
      ''
      else ''
        runHook preInstall

        mkdir -p "$out/Applications"
        mv Archi.app "$out/Applications/"

        runHook postInstall
      '';

    postFixup = ''
      # Fix the desktop file to use an absolute path to the bundled PNG icon
      # This must run in postFixup to ensure the desktop file has already been generated by copyDesktopItemsHook
      icon_path=$(find $out/libexec -name "app-64.png" | head -n 1)
      if [ -n "$icon_path" ] && [ -f "$out/share/applications/archi.desktop" ]; then
        sed -i 's|^Icon=.*|Icon='"$icon_path"'|' "$out/share/applications/archi.desktop"
      fi
    '';

    dontWrapGApps = false;

    desktopItems = [
      (makeDesktopItem {
        name = "archi";
        desktopName = "Archi";
        exec = "Archi";
        type = "Application";
        comment = "ArchiMate modelling toolkit";
        icon = "archi";
        categories = ["Development"];
      })
    ];

    passthru.tests = {archi = null;};

    meta = with lib; {
      description = "ArchiMate modelling toolkit";
      longDescription = ''
        Archi is an open source modelling toolkit to create ArchiMate
        models and sketches.
      '';
      homepage = "https://www.archimatetool.com/";
      sourceProvenance = with sourceTypes; [binaryNativeCode];
      license = licenses.mit;
      platforms = platforms.linux ++ platforms.darwin;
      mainProgram = "Archi";
    };
  }
