# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  analyzeMFT = {
    pname = "analyzeMFT";
    version = "v3.1.1.0";
    src = fetchFromGitHub {
      owner = "rowingdude";
      repo = "analyzeMFT";
      rev = "v3.1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-piCH88uQaRt3U1g+hfkBL1wVrN5C9v1sXVaAV6YQioo=";
    };
  };
  apk-mitm = {
    pname = "apk-mitm";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "niklashigi";
      repo = "apk-mitm";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-wcLShZ7O20i0hzz957dNmfjvxCn5lmWObTdTRF7p+I8=";
    };
  };
  archi = {
    pname = "archi";
    version = "5.9.0";
    src = fetchurl {
      url = "https://github.com/archimatetool/archi.io/releases/download/5.9.0/Archi-Linux64-5.9.0.tgz";
      sha256 = "sha256-0/3/EZw5upB0dvyhS0sfKqp7C4tc6vGDW+O9WU5iTc8=";
    };
  };
  ctf-dl = {
    pname = "ctf-dl";
    version = "db23c9dfe19429f3dfd75cf788cd54a8185f82e9";
    src = fetchgit {
      url = "https://github.com/bjornmorten/ctf-dl.git";
      rev = "db23c9dfe19429f3dfd75cf788cd54a8185f82e9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0n6CQAkpQLFJZsM767TxPcLIzzIfFyIMsf40pW5gNzc=";
    };
    date = "2025-10-12";
  };
  ctfbridge = {
    pname = "ctfbridge";
    version = "11f126d621e05dfe1e0b5b9cc5bd4c2f94220029";
    src = fetchgit {
      url = "https://github.com/bjornmorten/ctfbridge.git";
      rev = "11f126d621e05dfe1e0b5b9cc5bd4c2f94220029";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-gNuIVrRVn0zrTkoZnDNEjUY9QissWbGgkbNaLOBfd+8=";
    };
    date = "2026-03-06";
  };
  ctfd-parser = {
    pname = "ctfd-parser";
    version = "1.1";
    src = fetchFromGitHub {
      owner = "p0dalirius";
      repo = "ctfd-parser";
      rev = "1.1";
      fetchSubmodules = false;
      sha256 = "sha256-2Rbe97xz48r22X61jjnwFPBiN0dIeUKd4zcSJxBrSd0=";
    };
  };
  dnspy = {
    pname = "dnspy";
    version = "6.6.0";
    src = fetchurl {
      url = "https://github.com/dnSpyEx/dnSpy/releases/download/v6.6.0/dnSpy-netframework.zip";
      sha256 = "sha256-Lq239JMa0YgtEEd89XGF0ojKzG46v5lY565zwKDzHdE=";
    };
  };
  ese-database-view = {
    pname = "ese-database-view";
    version = "1.79";
    src = fetchurl {
      url = "https://www.nirsoft.net/utils/esedatabaseview.zip";
      sha256 = "sha256-tjbPXj7aom6tJE9YxK43LJoopQXRego6btTc5BusOr8=";
    };
  };
  evolve = {
    pname = "evolve";
    version = "v1.6";
    src = fetchFromGitHub {
      owner = "JamesHabben";
      repo = "evolve";
      rev = "v1.6";
      fetchSubmodules = false;
      sha256 = "sha256-IRO2pqRK3pMqv49T4U/aAccilIA9pdVURFTlSeXy5D4=";
    };
  };
  ffmpeg-encoder-plugin-resolve = {
    pname = "ffmpeg-encoder-plugin-resolve";
    version = "1.4.0";
    src = fetchurl {
      url = "https://github.com/EdvinNilsson/ffmpeg_encoder_plugin/releases/download/v1.4.0/ffmpeg_encoder_plugin.dvcp.bundle.zip";
      sha256 = "sha256-0Qzsd3h/JtjX8WzkFUBdFIxg/HUKFvP1p8K0b0Ai8UY=";
    };
  };
  harbor = {
    pname = "harbor";
    version = "0.9.21";
    src = fetchurl {
      url = "https://github.com/harborstremio-linux/harbor-linux-builds/releases/download/v0.9.21/Harbor_0.9.21_amd64.deb";
      sha256 = "sha256-j3TuBP4WDQj64k47LPRAiErchiQ4kKiuZ4cSMmKYkT0=";
    };
  };
  hayabusa = {
    pname = "hayabusa";
    version = "4.0.0";
    src = fetchurl {
      url = "https://github.com/Yamato-Security/hayabusa/releases/download/v4.0.0/hayabusa-4.0.0-lin-x64-gnu.zip";
      sha256 = "sha256-ETfifHleg/iDfJYvITbPFjSmemVde6jvqLLTijO6CbQ=";
    };
  };
  ida-chat-plugin = {
    pname = "ida-chat-plugin";
    version = "883f9b3550725d81eed80c25dd28c75b320f22c7";
    src = fetchFromGitHub {
      owner = "HexRaysSA";
      repo = "ida-chat-plugin";
      rev = "883f9b3550725d81eed80c25dd28c75b320f22c7";
      fetchSubmodules = false;
      sha256 = "sha256-ueGelV0KZhE4k7O5VsBTSfZgWz/gm9Lr3CdIYl99Yd8=";
    };
    date = "2026-04-20";
  };
  jackify = {
    pname = "jackify";
    version = "0.7.2.2";
    src = fetchurl {
      url = "https://github.com/Omni-guides/Jackify/releases/download/v0.7.2.2/Jackify.AppImage";
      sha256 = "sha256-Xc9XO/fSeqb52V2rzl2z50zG85SB+GkLxF7V3yiB1P0=";
    };
  };
  libesedb = {
    pname = "libesedb";
    version = "cf49b6d420d4a44dcd6355bc0d6b36f9f580f350";
    src = fetchgit {
      url = "https://github.com/libyal/libesedb.git";
      rev = "cf49b6d420d4a44dcd6355bc0d6b36f9f580f350";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TTDVXT+c/l1CU2UWWppA/OPu8YxP4AgqItCW0/FtFPU=";
    };
    date = "2026-07-04";
  };
  libfsntfs = {
    pname = "libfsntfs";
    version = "2eccb7a4356e919d50bb7f8956a683131141f0d3";
    src = fetchgit {
      url = "https://github.com/libyal/libfsntfs.git";
      rev = "2eccb7a4356e919d50bb7f8956a683131141f0d3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ZqM0OR5pBGEiqBs6NfwNZG6TAIDZXV1j5pHMpCMLQdM=";
    };
    date = "2026-07-27";
  };
  linoffice = {
    pname = "linoffice";
    version = "v2.2.10";
    src = fetchFromGitHub {
      owner = "eylenburg";
      repo = "linoffice";
      rev = "v2.2.10";
      fetchSubmodules = false;
      sha256 = "sha256-kLZEUZDz4rvUmVqvKVdMpAAmNdja56i81GaQ9jT+BLU=";
    };
  };
  monkeylauncher = {
    pname = "monkeylauncher";
    version = "0.2";
    src = fetchFromGitHub {
      owner = "SaruM4N3";
      repo = "MonkeyLauncher";
      rev = "0.2";
      fetchSubmodules = false;
      sha256 = "sha256-fHLKxU4gnKnuBhISZDHQIdcfRAYdxp5xGl9cPeNC5XM=";
    };
  };
  nordvpn = {
    pname = "nordvpn";
    version = "5.3.0";
    src = fetchurl {
      url = "https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/n/nordvpn/nordvpn_5.3.0_amd64.deb";
      sha256 = "sha256-NM3qcqdclwDChblQ7S7Jasru1NYHATo6vRg2ZzH4wzQ=";
    };
  };
  nuvio = {
    pname = "nuvio";
    version = "0.3.6.1";
    src = fetchurl {
      url = "https://github.com/blarns/NuvioForLinux/releases/download/v0.3.6.1/Nuvio-0.3.6.1-x86_64.AppImage";
      sha256 = "sha256-aG56lPtDo6e0NAhJXGxnWKE1RXcR8tJSRgUlRtJfTW0=";
    };
  };
  onlinefix-linux = {
    pname = "onlinefix-linux";
    version = "2.7.1";
    src = fetchurl {
      url = "https://github.com/ZzEdovec/onlinefix-linux/releases/download/v2.7.1/OFMELauncher.jar";
      sha256 = "sha256-nK5PLMBmaewaFHcQLR0lrPlvg5PJwdYcNyhCTS7cpdE=";
    };
  };
  registry-spy = {
    pname = "registry-spy";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "andyjsmith";
      repo = "Registry-Spy";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-5D6uDjcCFGtkAyMp0S3blwc5vMP39dyKWTM+nocSIm0=";
    };
  };
  rem = {
    pname = "rem";
    version = "1.4.0";
    src = fetchurl {
      url = "https://github.com/liriliri/rem/releases/download/v1.4.0/REM-1.4.0-linux-x86_64.AppImage";
      sha256 = "sha256-rL6ebeURL3dcts53xIq5olHHnEQoK9rzIPdfXbu3H/c=";
    };
  };
  reverser_ai = {
    pname = "reverser_ai";
    version = "1d572da70479ea822875b9350135d7e3402f5557";
    src = fetchFromGitHub {
      owner = "mrphrazer";
      repo = "reverser_ai";
      rev = "1d572da70479ea822875b9350135d7e3402f5557";
      fetchSubmodules = false;
      sha256 = "sha256-07bh4ofudKLKYGgHySSK4mpDstuyybKFktIfp0s8V8g=";
    };
    date = "2026-05-20";
  };
  scrollmpris = {
    pname = "scrollmpris";
    version = "27c0014a4bb6a74acc22879cc55b219681d87c1a";
    src = fetchFromGitHub {
      owner = "BEST8OY";
      repo = "ScrollMPRIS";
      rev = "27c0014a4bb6a74acc22879cc55b219681d87c1a";
      fetchSubmodules = false;
      sha256 = "sha256-ZxMVRDuxgO7cd6H+ovRpcUsUungli7rz93BKmA/zpJg=";
    };
    date = "2026-08-23";
  };
  sidr = {
    pname = "sidr";
    version = "v0.9.2";
    src = fetchFromGitHub {
      owner = "strozfriedberg";
      repo = "sidr";
      rev = "v0.9.2";
      fetchSubmodules = false;
      sha256 = "sha256-l6J+JJaFkFTDroMz6Ldnmq40OQGmEtL6l3ZFG6yk1GQ=";
    };
  };
  sstv = {
    pname = "sstv";
    version = "3e556eee8ad4c4425799cb652bac26ee58f8e113";
    src = fetchFromGitHub {
      owner = "colaclanth";
      repo = "sstv";
      rev = "3e556eee8ad4c4425799cb652bac26ee58f8e113";
      fetchSubmodules = false;
      sha256 = "sha256-s+G3MUVxEL/CwLaLk2nFcTFfRqq4Hrbj6qa/GhhzFMc=";
    };
    date = "2019-11-04";
  };
  steamidra = {
    pname = "steamidra";
    version = "v6.6.6";
    src = fetchFromGitHub {
      owner = "Midrags";
      repo = "SFF";
      rev = "v6.6.6";
      fetchSubmodules = false;
      sha256 = "sha256-75pGSL2qBJ0BsK6FLFyLk13I5nqvTgniaR6BgbYeK2o=";
    };
  };
  stremio-enhanced = {
    pname = "stremio-enhanced";
    version = "1.2.0";
    src = fetchurl {
      url = "https://github.com/REVENGE977/stremio-enhanced/releases/download/v1.2.0/Stremio.Enhanced-1.2.0.AppImage";
      sha256 = "sha256-a+knxg/rd5Ied4RVK8Gg7xeFElovJab0gqxpjs11fAU=";
    };
  };
  trakt-scrobbler = {
    pname = "trakt-scrobbler";
    version = "v1.9.0b1";
    src = fetchFromGitHub {
      owner = "iamkroot";
      repo = "trakt-scrobbler";
      rev = "v1.9.0b1";
      fetchSubmodules = false;
      sha256 = "sha256-ylgCDWmcZzz6mMBpEAj16jK1loTxQJmk9G/3Hnp9WuI=";
    };
  };
  volatility-toolkit = {
    pname = "volatility-toolkit";
    version = "v2.1.1";
    src = fetchFromGitHub {
      owner = "gl0bal01";
      repo = "volatility-toolkit";
      rev = "v2.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-2HdfpF1DCn95HsArcvAeuWh5FNwjj9LxwJ/nlosHBmk=";
    };
  };
}
